<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1ZWJaTs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1ZWJaTs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1ZWJaTs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1ZWJaTs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1ZWJaTs\App_KernelDevDebugContainer([
    'container.build_hash' => '1ZWJaTs',
    'container.build_id' => '42ab1913',
    'container.build_time' => 1581802724,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1ZWJaTs');
